language: python

sudo: false

cache: pip

env:
  - DJANGO='django>=1.11.0,<2.0.0'
  - DJANGO='django>=1.10.0,<1.11.0'
  - DJANGO='django>=1.9.0,<1.10.0'
  - DJANGO='django>=1.8.0,<1.9.0'

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

script: python tests.py

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install coveralls
  - travis_retry pip install -r requirements.txt

after_success:
    - coveralls
